# Generated by Django 6.0.3 on 2026-05-12 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_billing_patientrecord_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_reminder_24h', '24 Hour Reminder'), ('appointment_reminder_1h', '1 Hour Reminder'), ('waitlist_match', 'Waitlist Match Found'), ('waitlist_position', 'Waitlist Position Update'), ('billing_created', 'New Bill Created'), ('billing_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('overdue_payment', 'Overdue Payment Alert'), ('pencil_expiring', 'Pencil Booking Expiring'), ('reservation_expiring', 'Reservation Expiring'), ('ai_suggestion', 'AI Suggestion'), ('system_alert', 'System Alert'), ('promotion', 'Promotion/Announcement'), ('record_updated', 'Medical Record Updated'), ('treatment_plan', 'Treatment Plan Ready')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1)),
                ('delivery_channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_type', models.CharField(blank=True, max_length=100, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('appointment_id', models.IntegerField(blank=True, null=True)),
                ('bill_id', models.IntegerField(blank=True, null=True)),
                ('waitlist_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('both', 'Both')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('notify_appointment_reminders', models.BooleanField(default=True)),
                ('notify_appointment_confirmed', models.BooleanField(default=True)),
                ('notify_appointment_cancelled', models.BooleanField(default=True)),
                ('notify_waitlist_match', models.BooleanField(default=True)),
                ('notify_waitlist_position', models.BooleanField(default=True)),
                ('notify_billing_created', models.BooleanField(default=True)),
                ('notify_billing_reminders', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('notify_overdue_payment', models.BooleanField(default=True)),
                ('notify_ai_suggestions', models.BooleanField(default=True)),
                ('notify_system_alerts', models.BooleanField(default=True)),
                ('notify_promotions', models.BooleanField(default=False)),
                ('reminder_hours_before', models.IntegerField(default=24)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='users_notif_user_id_c58e16_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_delivered', 'created_at'], name='users_notif_is_deli_1905d4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='users_notif_expires_f9a864_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'priority', '-created_at'], name='users_notif_user_id_df7621_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'status'], name='users_notif_notific_c40df1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'created_at'], name='users_notif_channel_c80f2e_idx'),
        ),
    ]
