# Generated by Django 6.0.3 on 2026-05-12 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_notificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_deactivated', 'Account Deactivated'), ('account_reactivated', 'Account Reactivated'), ('appointment_created', 'Appointment Created'), ('appointment_updated', 'Appointment Updated'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_completed', 'Appointment Completed'), ('appointment_no_show', 'Appointment No-Show'), ('pencil_booking_created', 'Pencil Booking Created'), ('pencil_booking_expired', 'Pencil Booking Expired'), ('pencil_booking_confirmed', 'Pencil Booking Confirmed'), ('waitlist_joined', 'Joined Waitlist'), ('waitlist_left', 'Left Waitlist'), ('waitlist_notified', 'Waitlist Notified'), ('waitlist_booked', 'Waitlist Booked'), ('payment_made', 'Payment Made'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('payment_refunded', 'Payment Refunded'), ('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_paid', 'Invoice Paid'), ('braces_downpayment_approved', 'Braces Downpayment Approved'), ('bill_overdue', 'Bill Marked Overdue'), ('patient_record_created', 'Patient Record Created'), ('patient_record_updated', 'Patient Record Updated'), ('patient_record_viewed', 'Patient Record Viewed'), ('treatment_history_added', 'Treatment History Added'), ('treatment_history_updated', 'Treatment History Updated'), ('medical_certificate_issued', 'Medical Certificate Issued'), ('ai_suggestion_generated', 'AI Suggestion Generated'), ('notification_sent', 'Notification Sent'), ('notification_read', 'Notification Read'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('admin_user_created', 'Admin Created User'), ('admin_user_updated', 'Admin Updated User'), ('admin_user_deleted', 'Admin Deleted User'), ('admin_role_changed', 'Admin Role Changed'), ('admin_settings_updated', 'Admin Settings Updated'), ('admin_report_generated', 'Admin Report Generated'), ('admin_data_exported', 'Admin Data Exported'), ('admin_backup_created', 'Admin Backup Created'), ('system_error', 'System Error'), ('system_maintenance', 'System Maintenance'), ('database_backup', 'Database Backup'), ('cache_cleared', 'Cache Cleared'), ('celery_task_started', 'Celery Task Started'), ('celery_task_completed', 'Celery Task Completed'), ('celery_task_failed', 'Celery Task Failed'), ('suspicious_activity', 'Suspicious Activity Detected'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('permission_denied', 'Permission Denied'), ('data_import', 'Data Import'), ('data_export', 'Data Export'), ('data_deleted', 'Data Deleted'), ('bulk_operation', 'Bulk Operation')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('entity_type', models.CharField(blank=True, choices=[('user', 'User'), ('appointment', 'Appointment'), ('billing', 'Billing'), ('payment', 'Payment'), ('patient_record', 'Patient Record'), ('treatment_history', 'Treatment History'), ('waitlist', 'Waitlist'), ('notification', 'Notification'), ('ai_suggestion', 'AI Suggestion'), ('booking_reservation', 'Booking Reservation'), ('system', 'System'), ('admin', 'Admin Action')], db_index=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('entity_string', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('database_queries', models.IntegerField(blank=True, help_text='Number of database queries', null=True)),
                ('is_success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', '-created_at'], name='users_activ_user_id_d57a7d_idx'), models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='users_activ_entity__0d0b9b_idx'), models.Index(fields=['severity', '-created_at'], name='users_activ_severit_35d7f1_idx'), models.Index(fields=['created_at'], name='users_activ_created_31380b_idx'), models.Index(fields=['ip_address', '-created_at'], name='users_activ_ip_addr_739f84_idx'), models.Index(fields=['session_id', '-created_at'], name='users_activ_session_73343f_idx'), models.Index(fields=['request_id'], name='users_activ_request_46416c_idx'), models.Index(fields=['is_success', '-created_at'], name='users_activ_is_succ_abc1b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(db_index=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id', '-created_at'], name='users_audit_model_n_997855_idx'), models.Index(fields=['user', '-created_at'], name='users_audit_user_id_949877_idx'), models.Index(fields=['operation', '-created_at'], name='users_audit_operati_64685b_idx')],
            },
        ),
    ]
